name: Bump version (cron)
permissions:
  contents: write

on:
  schedule:
    - cron: "15 3 * * TUE"

jobs:
  scheduled_bump:
    uses: ./.github/workflows/bump.yml
    secrets: inherit
    with:
      semver: minor
