name: Secretlint
on: push
permissions:
  contents: read
jobs:
  test:
    name: "Secretlint"
    runs-on: ubuntu-22.04
    container: secretlint/secretlint:v8.1.0
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: Lint with Secretlint
        run: secretlint "**/*"
